# [TIMESTAMP: 2026-06-07T23:25:00.000Z] [PROJECT_ID: SimsMerged-v1.4.2] [AGENT_ID: viper_cli-architectssj4]

import subprocess
import os
import sys
import time

from .config import SSD_SANDBOX_PATH, RESEARCH_DIR, FOUNDRY_DIR, sandbox_guard
from .proot_controller import proot_controller

class CodeExecutionSandbox:
    """
    STRICT CODE EXECUTION SANDBOX:
    - Runs Python/JS scripts generated by agents.
    - Restricted entirely to the physical SSD_SANDBOX.
    - Integrated with PROOT isolation for per-agent hard-fencing.
    """
    def __init__(self):
        self.sandbox_dir = SSD_SANDBOX_PATH
        self.execution_log = os.path.join(self.sandbox_dir, "execution_history.log")

    def run_script(self, filename, agent_id: str = None):
        """Executes a script and returns the result/errors."""
        try:
            # 1. Physical Isolation Check (PROOT)
            if agent_id:
                cmd = f"{sys.executable} {filename}" if filename.endswith(".py") else f"node {filename}"
                return proot_controller.execute_in_sandbox(agent_id, cmd)

            # 2. Standard Sandbox Fallback
            filepath = sandbox_guard(os.path.join(RESEARCH_DIR, filename))
            if not os.path.exists(filepath):
                filepath = sandbox_guard(os.path.join(FOUNDRY_DIR, filename))
            if not os.path.exists(filepath):
                filepath = sandbox_guard(os.path.join(SSD_SANDBOX_PATH, "build_lab", filename))
            if not os.path.exists(filepath):
                filepath = sandbox_guard(os.path.join(SSD_SANDBOX_PATH, "assembly_line", filename))
            
            if not os.path.exists(filepath):
                return f"ERR: File {filename} not found in sandbox."

            start_time = time.time()
            if filename.endswith(".py"):
                cmd = [sys.executable, filepath]
            elif filename.endswith(".js"):
                cmd = ["node", filepath]
            else:
                return "ERR: Unsupported file type for execution."

            result = subprocess.run(
                cmd, capture_output=True, text=True, timeout=5.0,
                cwd=self.sandbox_dir
            )
            
            elapsed = time.time() - start_time
            output = result.stdout if result.stdout else result.stderr
            
            with open(self.execution_log, "a") as f:
                f.write(f"[{time.ctime()}] EXECUTED: {filename} | DURATION: {elapsed:.2f}s | STATUS: {result.returncode}\n")
            
            return f"SUCCESS (Exit {result.returncode}): {output[:200]}"
        except subprocess.TimeoutExpired:
            return "ERR: Execution TIMED OUT (Fenced safety limit reached)."
        except Exception as e:
            return f"ERR: Execution Failed: {str(e)}"

execution_sandbox = CodeExecutionSandbox()
